version: '3.2'

services:

 api:
   depends_on:
     - store
   build: ./images/api
   ports:
     - 80:3000
   volumes:
     - ./images/api/src:/usr/app/src
   environment:
     PG_CONNECTION_STRING: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@store:5432/${POSTGRES_DB}"

 frontend:
    depends_on:
      - api
    build:
      context: ./images/front
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./images/front/src:/usr/src/app/src

 store:
    container_name: store
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST:
      POSTGRES_USER:
      POSTGRES_DB:
      POSTGRES_PASSWORD:
    volumes:
      - ./_backup:/var/lib/postgresql/data

 watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30